import {
  ArchiveBoxIcon as ArchiveBox,
  Bars4Icon as Bars4,
  XMarkIcon as XMark,
  Bars2Icon as Bars2,
  MapPinIcon as MapPin,
  BookmarkIcon as Bookmark,
  CalendarDaysIcon as CalendarDays,
  ChevronDownIcon as ChevronDown,
  ChevronLeftIcon as ChevronLeft,
  ChevronRightIcon as ChevronRight,
  ChevronUpIcon as ChevronUp,
  ArrowUturnLeftIcon as ArrowUturnLeft,
  ArrowUpTrayIcon as ArrowUpTray,
  ClockIcon as Clock,
  TableCellsIcon as TableCells,
  ChartBarSquareIcon as ChartBarSquare,
  FlagIcon as Flag,
  FolderIcon as Folder,
  FolderOpenIcon as FolderOpen,
  HeartIcon as Heart,
  MagnifyingGlassIcon as MagnifyingGlass,
  PlusIcon as Plus,
  RssIcon as Rss,
  Cog8ToothIcon as Cog8Tooth,
  WalletIcon as Wallet,
  ShoppingBagIcon as ShoppingBag,
  TagIcon as Tag,
  ViewColumnsIcon as ViewColumns,
  WindowIcon as Window,
  PlusCircleIcon as PlusCircle,
  NewspaperIcon as Newspaper,
  ArrowPathIcon as ArrowPath,
  Squares2X2Icon as Squares2X2,
  SquaresPlusIcon as SquaresPlus,
  TrashIcon as Trash,
  BookOpenIcon as BookOpen,
  ArrowLeftIcon as ArrowLeft,
  ArrowRightIcon as ArrowRight,
  ArrowUpOnSquareIcon as ArrowUpOnSquare,
  DocumentTextIcon as DocumentText,
  BanknotesIcon as Banknotes,
  CreditCardIcon as CreditCard,
  ReceiptPercentIcon as ReceiptPercent,
  ReceiptRefundIcon as ReceiptRefund,
  HomeIcon as Home,
  LightBulbIcon as LightBulb,
  PresentationChartLineIcon as PresentationChartLine,
  ChartBarIcon as ChartBar,
  ChartPieIcon as ChartPie,
  ClipboardDocumentListIcon as ClipboardDocumentList,
  CurrencyDollarIcon as CurrencyDollar,
  CurrencyEuroIcon as CurrencyEuro,
  CurrencyYenIcon as CurrencyYen,
  CubeIcon as Cube,
  CubeTransparentIcon as CubeTransparent,
  KeyIcon as Key,
  LifebuoyIcon as Lifebuoy,
  BoltIcon as Bolt,
  PaperClipIcon as PaperClip,
  BuildingOfficeIcon as BuildingOffice,
  BuildingOffice2Icon as BuildingOffice2,
  GiftTopIcon as GiftTop,
  FilmIcon as Film,
  GiftIcon as Gift,
  TicketIcon as Ticket,
  MusicalNoteIcon as MusicalNote,
  TvIcon as TV,
  TruckIcon as Truck,
  ArrowTrendingUpIcon as ArrowTrendingUp,
  ArrowTrendingDownIcon as ArrowTrendingDown,
  WifiIcon as Wifi,
  EyeDropperIcon as EyeDropper,
  ShoppingCartIcon as ShoppingCart,
  HomeModernIcon as HomeModern,
  AcademicCapIcon as AcademicCap,
  ShieldCheckIcon as ShieldCheck,
  EllipsisHorizontalCircleIcon as EllipsisHorizontalCircle,
  BeakerIcon as Beaker,
  ScaleIcon as Scale,
  CircleStackIcon as CircleStack,
  LanguageIcon as Language,
  ExclamationTriangleIcon as ExclamationTriangle,
  PaperAirplaneIcon as PaperAirplane,
  PaintBrushIcon as PaintBrush,
  MegaphoneIcon as Megaphone,
  CakeIcon as Cake,
  ChevronDoubleRightIcon as ChevronDoubleRight,
  CheckIcon as Check,
  QueueListIcon as QueueList,
  SparklesIcon as Sparkles,
  UserIcon as User,
  PencilIcon as Pencil,
  EyeIcon as Eye,
  BuildingStorefrontIcon as BuildingStorefront,
  ChevronUpDownIcon as ChevronUpDown,
  AtSymbolIcon as AtSymbol,
  WrenchScrewdriverIcon as WrenchScrewdriver,
  BuildingLibraryIcon as BuildingLibrary,
  ClipboardDocumentCheckIcon as ClipboardDocumentCheck,
  ClipboardDocumentIcon as ClipboardDocument,
  BriefcaseIcon as Briefcase,
  CloudIcon as Cloud,
  CloudArrowDownIcon as CloudArrowDown,
  CloudArrowUpIcon as CloudArrowUp,
  LinkIcon as Link,
  RectangleStackIcon as RectangleStack,
  PrinterIcon as Printer,
} from '@heroicons/react/24/outline'

import classNames from 'classnames'
import { PlusCircleIcon as SolidPlusCircle } from '@heroicons/react/24/solid'

const ICONS = {
  Link,
  Printer,
  RectangleStack,
  Pencil,
  Briefcase,
  MapPin,
  Eye,
  XMark,
  AtSymbol,
  ChevronUpDown,
  BuildingStorefront,
  BuildingLibrary,
  ClipboardDocument,
  ChartBarSquare,
  Bolt,
  QueueList,
  WrenchScrewdriver,
  User,
  Ticket,
  Sparkles,
  Truck,
  Cube,
  CubeTransparent,
  Language,
  ChevronDoubleRight,
  Scale,
  ShieldCheck,
  EyeDropper,
  Beaker,
  EllipsisHorizontalCircle,
  ExclamationTriangle,
  AcademicCap,
  ArrowRight,
  ArrowTrendingUp,
  ArrowTrendingDown,
  ArrowUpTray,
  HomeModern,
  ArrowLeft,
  CircleStack,
  PaintBrush,
  Megaphone,
  ClipboardDocumentCheck,
  TV,
  ChartBar,
  Lifebuoy,
  Wifi,
  Cake,
  Film,
  PaperAirplane,
  MusicalNote,
  PaperClip,
  ShoppingCart,
  ChartPie,
  Heart,
  Clock,
  Flag,
  Folder,
  FolderOpen,
  Tag,
  Rss,
  Bookmark,
  BookOpen,
  Window,
  CalendarDays,
  ShoppingBag,
  ChevronDown,
  ChevronRight,
  ChevronLeft,
  ChevronUp,
  MagnifyingGlass,
  ViewColumns,
  PlusCircle,
  SolidPlusCircle,
  Plus,
  ArchiveBox,
  Bars2,
  Newspaper,
  ArrowPath,
  ArrowUpOnSquare,
  SquaresPlus,
  Squares2X2,
  Trash,
  DocumentText,
  Banknotes,
  CreditCard,
  ReceiptPercent,
  ReceiptRefund,
  CurrencyDollar,
  Key,
  BuildingOffice,
  GiftTop,
  Gift,
  BuildingOffice2,
  Wallet,
  Home,
  LightBulb,
  PresentationChartLine,
  ClipboardDocumentList,
  Check,
  ArrowUturnLeft,
  Cog8Tooth,
  Cloud,
  CloudArrowUp,
  CloudArrowDown,
  CurrencyEuro,
  CurrencyYen,
  Bars4,
  TableCells,
}

export default function Icon({ name, className, ...props }) {
  const IC = ICONS[name]
  if (!IC) return <></>
  return <IC className={classNames('icon', className)} {...props} />
}
