export const SummerianLetters = {
  '𒀀': 'A',
  '𒀁': 'A TIMES A',
  '𒀂': 'A TIMES BAD',
  '𒀃': 'A TIMES GAN2 TENU',
  '𒀄': 'A TIMES HA',
  '𒀅': 'A TIMES IGI',
  '𒀆': 'A TIMES LAGAR GUNU',
  '𒀇': 'A TIMES MUSH',
  '𒀈': 'A TIMES SAG',
  '𒀉': 'A2',
  '𒀊': 'AB',
  '𒀋': 'AB TIMES ASH2',
  '𒀌': 'AB TIMES DUN3 GUNU',
  '𒀍': 'AB TIMES GAL',
  '𒀎': 'AB TIMES GAN2 TENU',
  '𒀏': 'AB TIMES HA',
  '𒀐': 'AB TIMES IGI GUNU',
  '𒀑': 'AB TIMES IMIN',
  '𒀒': 'AB TIMES LAGAB',
  '𒀓': 'AB TIMES SHESH',
  '𒀔': 'AB TIMES U PLUS U PLUS U',
  '𒀕': 'AB GUNU',
  '𒀖': 'AB2',
  '𒀗': 'AB2 TIMES BALAG',
  '𒀘': 'AB2 TIMES GAN2 TENU',
  '𒀙': 'AB2 TIMES ME PLUS EN',
  '𒀚': 'AB2 TIMES SHA3',
  '𒀛': 'AB2 TIMES TAK4',
  '𒀜': 'AD',
  '𒀝': 'AK',
  '𒀞': 'AK TIMES ERIN2',
  '𒀟': 'AK TIMES SHITA PLUS GISH',
  '𒀠': 'AL',
  '𒀡': 'AL TIMES AL',
  '𒀢': 'AL TIMES DIM2',
  '𒀣': 'AL TIMES GISH',
  '𒀤': 'AL TIMES HA',
  '𒀥': 'AL TIMES KAD3',
  '𒀦': 'AL TIMES KI',
  '𒀧': 'AL TIMES SHE',
  '𒀨': 'AL TIMES USH',
  '𒀩': 'ALAN',
  '𒀪': 'ALEPH',
  '𒀫': 'AMAR',
  '𒀬': 'AMAR TIMES SHE',
  '𒀭': 'AN',
  '𒀮': 'AN OVER AN',
  '𒀯': 'AN THREE TIMES',
  '𒀰': 'AN PLUS NAGA OPPOSING AN PLUS NAGA',
  '𒀱': 'AN PLUS NAGA SQUARED',
  '𒀲': 'ANSHE',
  '𒀳': 'APIN',
  '𒀴': 'ARAD',
  '𒀵': 'ARAD TIMES KUR',
  '𒀶': 'ARKAB',
  '𒀷': 'ASAL2',
  '𒀸': 'ASH',
  '𒀹': 'ASH ZIDA TENU',
  '𒀺': 'ASH KABA TENU',
  '𒀻': 'ASH OVER ASH TUG2 OVER TUG2 TUG2 OVER TUG2 PAP',
  '𒀼': 'ASH OVER ASH OVER ASH',
  '𒀽': 'ASH OVER ASH OVER ASH CROSSING ASH OVER ASH OVER ASH',
  '𒀾': 'ASH2',
  '𒀿': 'ASHGAB',
  '𒁀': 'BA',
  '𒁁': 'BAD',
  '𒁂': 'BAG3',
  '𒁃': 'BAHAR2',
  '𒁄': 'BAL',
  '𒁅': 'BAL OVER BAL',
  '𒁆': 'BALAG',
  '𒁇': 'BAR',
  '𒁈': 'BARA2',
  '𒁉': 'BI',
  '𒁊': 'BI TIMES A',
  '𒁋': 'BI TIMES GAR',
  '𒁌': 'BI TIMES IGI GUNU',
  '𒁍': 'BU',
  '𒁎': 'BU OVER BU AB',
  '𒁏': 'BU OVER BU UN',
  '𒁐': 'BU CROSSING BU',
  '𒁑': 'BULUG',
  '𒁒': 'BULUG OVER BULUG',
  '𒁓': 'BUR',
  '𒁔': 'BUR2',
  '𒁕': 'DA',
  '𒁖': 'DAG',
  '𒁗': 'DAG KISIM5 TIMES A PLUS MASH',
  '𒁘': 'DAG KISIM5 TIMES AMAR',
  '𒁙': 'DAG KISIM5 TIMES BALAG',
  '𒁚': 'DAG KISIM5 TIMES BI',
  '𒁛': 'DAG KISIM5 TIMES GA',
  '𒁜': 'DAG KISIM5 TIMES GA PLUS MASH',
  '𒁝': 'DAG KISIM5 TIMES GI',
  '𒁞': 'DAG KISIM5 TIMES GIR2',
  '𒁟': 'DAG KISIM5 TIMES GUD',
  '𒁠': 'DAG KISIM5 TIMES HA',
  '𒁡': 'DAG KISIM5 TIMES IR',
  '𒁢': 'DAG KISIM5 TIMES IR PLUS LU',
  '𒁣': 'DAG KISIM5 TIMES KAK',
  '𒁤': 'DAG KISIM5 TIMES LA',
  '𒁥': 'DAG KISIM5 TIMES LU',
  '𒁦': 'DAG KISIM5 TIMES LU PLUS MASH2',
  '𒁧': 'DAG KISIM5 TIMES LUM',
  '𒁨': 'DAG KISIM5 TIMES NE',
  '𒁩': 'DAG KISIM5 TIMES PAP PLUS PAP',
  '𒁪': 'DAG KISIM5 TIMES SI',
  '𒁫': 'DAG KISIM5 TIMES TAK4',
  '𒁬': 'DAG KISIM5 TIMES U2 PLUS GIR2',
  '𒁭': 'DAG KISIM5 TIMES USH',
  '𒁮': 'DAM',
  '𒁯': 'DAR',
  '𒁰': 'DARA3',
  '𒁱': 'DARA4',
  '𒁲': 'DI',
  '𒁳': 'DIB',
  '𒁴': 'DIM',
  '𒁵': 'DIM TIMES SHE',
  '𒁶': 'DIM2',
  '𒁷': 'DIN',
  '𒁸': 'DIN KASKAL U GUNU DISH',
  '𒁹': 'DISH',
  '𒁺': 'DU',
  '𒁻': 'DU OVER DU',
  '𒁼': 'DU GUNU',
  '𒁽': 'DU SHESHIG',
  '𒁾': 'DUB',
  '𒁿': 'DUB TIMES ESH2',
  '𒂀': 'DUB2',
  '𒂁': 'DUG',
  '𒂂': 'DUGUD',
  '𒂃': 'DUH',
  '𒂄': 'DUN',
  '𒂅': 'DUN3',
  '𒂆': 'DUN3 GUNU',
  '𒂇': 'DUN3 GUNU GUNU',
  '𒂈': 'DUN4',
  '𒂉': 'DUR2',
  '𒂊': 'E',
  '𒂋': 'E TIMES PAP',
  '𒂌': 'E OVER E NUN OVER NUN',
  '𒂍': 'E2',
  '𒂎': 'E2 TIMES A PLUS HA PLUS DA',
  '𒂏': 'E2 TIMES GAR',
  '𒂐': 'E2 TIMES MI',
  '𒂑': 'E2 TIMES SAL',
  '𒂒': 'E2 TIMES SHE',
  '𒂓': 'E2 TIMES U',
  '𒂔': 'EDIN',
  '𒂕': 'EGIR',
  '𒂖': 'EL',
  '𒂗': 'EN',
  '𒂘': 'EN TIMES GAN2',
  '𒂙': 'EN TIMES GAN2 TENU',
  '𒂚': 'EN TIMES ME',
  '𒂛': 'EN CROSSING EN',
  '𒂜': 'EN OPPOSING EN',
  '𒂝': 'EN SQUARED',
  '𒂞': 'EREN',
  '𒂟': 'ERIN2',
  '𒂠': 'ESH2',
  '𒂡': 'EZEN',
  '𒂢': 'EZEN TIMES A',
  '𒂣': 'EZEN TIMES A PLUS LAL',
  '𒂤': 'EZEN TIMES A PLUS LAL TIMES LAL',
  '𒂥': 'EZEN TIMES AN',
  '𒂦': 'EZEN TIMES BAD',
  '𒂧': 'EZEN TIMES DUN3 GUNU',
  '𒂨': 'EZEN TIMES DUN3 GUNU GUNU',
  '𒂩': 'EZEN TIMES HA',
  '𒂪': 'EZEN TIMES HA GUNU',
  '𒂫': 'EZEN TIMES IGI GUNU',
  '𒂬': 'EZEN TIMES KASKAL',
  '𒂭': 'EZEN TIMES KASKAL SQUARED',
  '𒂮': 'EZEN TIMES KU3',
  '𒂯': 'EZEN TIMES LA',
  '𒂰': 'EZEN TIMES LAL TIMES LAL',
  '𒂱': 'EZEN TIMES LI',
  '𒂲': 'EZEN TIMES LU',
  '𒂳': 'EZEN TIMES U2',
  '𒂴': 'EZEN TIMES UD',
  '𒂵': 'GA',
  '𒂶': 'GA GUNU',
  '𒂷': 'GA2',
  '𒂸': 'GA2 TIMES A PLUS DA PLUS HA',
  '𒂹': 'GA2 TIMES A PLUS HA',
  '𒂺': 'GA2 TIMES A PLUS IGI',
  '𒂻': 'GA2 TIMES AB2 TENU PLUS TAB',
  '𒂼': 'GA2 TIMES AN',
  '𒂽': 'GA2 TIMES ASH',
  '𒂾': 'GA2 TIMES ASH2 PLUS GAL',
  '𒂿': 'GA2 TIMES BAD',
  '𒃀': 'GA2 TIMES BAR PLUS RA',
  '𒃁': 'GA2 TIMES BUR',
  '𒃂': 'GA2 TIMES BUR PLUS RA',
  '𒃃': 'GA2 TIMES DA',
  '𒃄': 'GA2 TIMES DI',
  '𒃅': 'GA2 TIMES DIM TIMES SHE',
  '𒃆': 'GA2 TIMES DUB',
  '𒃇': 'GA2 TIMES EL',
  '𒃈': 'GA2 TIMES EL PLUS LA',
  '𒃉': 'GA2 TIMES EN',
  '𒃊': 'GA2 TIMES EN TIMES GAN2 TENU',
  '𒃋': 'GA2 TIMES GAN2 TENU',
  '𒃌': 'GA2 TIMES GAR',
  '𒃍': 'GA2 TIMES GI',
  '𒃎': 'GA2 TIMES GI4',
  '𒃏': 'GA2 TIMES GI4 PLUS A',
  '𒃐': 'GA2 TIMES GIR2 PLUS SU',
  '𒃑': 'GA2 TIMES HA PLUS LU PLUS ESH2',
  '𒃒': 'GA2 TIMES HAL',
  '𒃓': 'GA2 TIMES HAL PLUS LA',
  '𒃔': 'GA2 TIMES HI PLUS LI',
  '𒃕': 'GA2 TIMES HUB2',
  '𒃖': 'GA2 TIMES IGI GUNU',
  '𒃗': 'GA2 TIMES ISH PLUS HU PLUS ASH',
  '𒃘': 'GA2 TIMES KAK',
  '𒃙': 'GA2 TIMES KASKAL',
  '𒃚': 'GA2 TIMES KID',
  '𒃛': 'GA2 TIMES KID PLUS LAL',
  '𒃜': 'GA2 TIMES KU3 PLUS AN',
  '𒃝': 'GA2 TIMES LA',
  '𒃞': 'GA2 TIMES ME PLUS EN',
  '𒃟': 'GA2 TIMES MI',
  '𒃠': 'GA2 TIMES NUN',
  '𒃡': 'GA2 TIMES NUN OVER NUN',
  '𒃢': 'GA2 TIMES PA',
  '𒃣': 'GA2 TIMES SAL',
  '𒃤': 'GA2 TIMES SAR',
  '𒃥': 'GA2 TIMES SHE',
  '𒃦': 'GA2 TIMES SHE PLUS TUR',
  '𒃧': 'GA2 TIMES SHID',
  '𒃨': 'GA2 TIMES SUM',
  '𒃩': 'GA2 TIMES TAK4',
  '𒃪': 'GA2 TIMES U',
  '𒃫': 'GA2 TIMES UD',
  '𒃬': 'GA2 TIMES UD PLUS DU',
  '𒃭': 'GA2 OVER GA2',
  '𒃮': 'GABA',
  '𒃯': 'GABA CROSSING GABA',
  '𒃰': 'GAD',
  '𒃱': 'GAD OVER GAD GAR OVER GAR',
  '𒃲': 'GAL',
  '𒃳': 'GAL GAD OVER GAD GAR OVER GAR',
  '𒃴': 'GALAM',
  '𒃵': 'GAM',
  '𒃶': 'GAN',
  '𒃷': 'GAN2',
  '𒃸': 'GAN2 TENU',
  '𒃹': 'GAN2 OVER GAN2',
  '𒃺': 'GAN2 CROSSING GAN2',
  '𒃻': 'GAR',
  '𒃼': 'GAR3',
  '𒃽': 'GASHAN',
  '𒃾': 'GESHTIN',
  '𒃿': 'GESHTIN TIMES KUR',
  '𒄀': 'GI',
  '𒄁': 'GI TIMES E',
  '𒄂': 'GI TIMES U',
  '𒄃': 'GI CROSSING GI',
  '𒄄': 'GI4',
  '𒄅': 'GI4 OVER GI4',
  '𒄆': 'GI4 CROSSING GI4',
  '𒄇': 'GIDIM',
  '𒄈': 'GIR2',
  '𒄉': 'GIR2 GUNU',
  '𒄊': 'GIR3',
  '𒄋': 'GIR3 TIMES A PLUS IGI',
  '𒄌': 'GIR3 TIMES GAN2 TENU',
  '𒄍': 'GIR3 TIMES IGI',
  '𒄎': 'GIR3 TIMES LU PLUS IGI',
  '𒄏': 'GIR3 TIMES PA',
  '𒄐': 'GISAL',
  '𒄑': 'GISH',
  '𒄒': 'GISH CROSSING GISH',
  '𒄓': 'GISH TIMES BAD',
  '𒄔': 'GISH TIMES TAK4',
  '𒄕': 'GISH TENU',
  '𒄖': 'GU',
  '𒄗': 'GU CROSSING GU',
  '𒄘': 'GU2',
  '𒄙': 'GU2 TIMES KAK',
  '𒄚': 'GU2 TIMES KAK TIMES IGI GUNU',
  '𒄛': 'GU2 TIMES NUN',
  '𒄜': 'GU2 TIMES SAL PLUS TUG2',
  '𒄝': 'GU2 GUNU',
  '𒄞': 'GUD',
  '𒄟': 'GUD TIMES A PLUS KUR',
  '𒄠': 'GUD TIMES KUR',
  '𒄡': 'GUD OVER GUD LUGAL',
  '𒄢': 'GUL',
  '𒄣': 'GUM',
  '𒄤': 'GUM TIMES SHE',
  '𒄥': 'GUR',
  '𒄦': 'GUR7',
  '𒄧': 'GURUN',
  '𒄨': 'GURUSH',
  '𒄩': 'HA',
  '𒄪': 'HA TENU',
  '𒄫': 'HA GUNU',
  '𒄬': 'HAL',
  '𒄭': 'HI',
  '𒄮': 'HI TIMES ASH',
  '𒄯': 'HI TIMES ASH2',
  '𒄰': 'HI TIMES BAD',
  '𒄱': 'HI TIMES DISH',
  '𒄲': 'HI TIMES GAD',
  '𒄳': 'HI TIMES KIN',
  '𒄴': 'HI TIMES NUN',
  '𒄵': 'HI TIMES SHE',
  '𒄶': 'HI TIMES U',
  '𒄷': 'HU',
  '𒄸': 'HUB2',
  '𒄹': 'HUB2 TIMES AN',
  '𒄺': 'HUB2 TIMES HAL',
  '𒄻': 'HUB2 TIMES KASKAL',
  '𒄼': 'HUB2 TIMES LISH',
  '𒄽': 'HUB2 TIMES UD',
  '𒄾': 'HUL2',
  '𒄿': 'I',
  '𒅀': 'I A',
  '𒅁': 'IB',
  '𒅂': 'IDIM',
  '𒅃': 'IDIM OVER IDIM BUR',
  '𒅄': 'IDIM OVER IDIM SQUARED',
  '𒅅': 'IG',
  '𒅆': 'IGI',
  '𒅇': 'IGI DIB',
  '𒅈': 'IGI RI',
  '𒅉': 'IGI OVER IGI SHIR OVER SHIR UD OVER UD',
  '𒅊': 'IGI GUNU',
  '𒅋': 'IL',
  '𒅌': 'IL TIMES GAN2 TENU',
  '𒅍': 'IL2',
  '𒅎': 'IM',
  '𒅏': 'IM TIMES TAK4',
  '𒅐': 'IM CROSSING IM',
  '𒅑': 'IM OPPOSING IM',
  '𒅒': 'IM SQUARED',
  '𒅓': 'IMIN',
  '𒅔': 'IN',
  '𒅕': 'IR',
  '𒅖': 'ISH',
  '𒅗': 'KA',
  '𒅘': 'KA TIMES A',
  '𒅙': 'KA TIMES AD',
  '𒅚': 'KA TIMES AD PLUS KU3',
  '𒅛': 'KA TIMES ASH2',
  '𒅜': 'KA TIMES BAD',
  '𒅝': 'KA TIMES BALAG',
  '𒅞': 'KA TIMES BAR',
  '𒅟': 'KA TIMES BI',
  '𒅠': 'KA TIMES ERIN2',
  '𒅡': 'KA TIMES ESH2',
  '𒅢': 'KA TIMES GA',
  '𒅣': 'KA TIMES GAL',
  '𒅤': 'KA TIMES GAN2 TENU',
  '𒅥': 'KA TIMES GAR',
  '𒅦': 'KA TIMES GAR PLUS SHA3 PLUS A',
  '𒅧': 'KA TIMES GI',
  '𒅨': 'KA TIMES GIR2',
  '𒅩': 'KA TIMES GISH PLUS SAR',
  '𒅪': 'KA TIMES GISH CROSSING GISH',
  '𒅫': 'KA TIMES GU',
  '𒅬': 'KA TIMES GUR7',
  '𒅭': 'KA TIMES IGI',
  '𒅮': 'KA TIMES IM',
  '𒅯': 'KA TIMES KAK',
  '𒅰': 'KA TIMES KI',
  '𒅱': 'KA TIMES KID',
  '𒅲': 'KA TIMES LI',
  '𒅳': 'KA TIMES LU',
  '𒅴': 'KA TIMES ME',
  '𒅵': 'KA TIMES ME PLUS DU',
  '𒅶': 'KA TIMES ME PLUS GI',
  '𒅷': 'KA TIMES ME PLUS TE',
  '𒅸': 'KA TIMES MI',
  '𒅹': 'KA TIMES MI PLUS NUNUZ',
  '𒅺': 'KA TIMES NE',
  '𒅻': 'KA TIMES NUN',
  '𒅼': 'KA TIMES PI',
  '𒅽': 'KA TIMES RU',
  '𒅾': 'KA TIMES SA',
  '𒅿': 'KA TIMES SAR',
  '𒆀': 'KA TIMES SHA',
  '𒆁': 'KA TIMES SHE',
  '𒆂': 'KA TIMES SHID',
  '𒆃': 'KA TIMES SHU',
  '𒆄': 'KA TIMES SIG',
  '𒆅': 'KA TIMES SUHUR',
  '𒆆': 'KA TIMES TAR',
  '𒆇': 'KA TIMES U',
  '𒆈': 'KA TIMES U2',
  '𒆉': 'KA TIMES UD',
  '𒆊': 'KA TIMES UMUM TIMES PA',
  '𒆋': 'KA TIMES USH',
  '𒆌': 'KA TIMES ZI',
  '𒆍': 'KA2',
  '𒆎': 'KA2 CROSSING KA2',
  '𒆏': 'KAB',
  '𒆐': 'KAD2',
  '𒆑': 'KAD3',
  '𒆒': 'KAD4',
  '𒆓': 'KAD5',
  '𒆔': 'KAD5 OVER KAD5',
  '𒆕': 'KAK',
  '𒆖': 'KAK TIMES IGI GUNU',
  '𒆗': 'KAL',
  '𒆘': 'KAL TIMES BAD',
  '𒆙': 'KAL CROSSING KAL',
  '𒆚': 'KAM2',
  '𒆛': 'KAM4',
  '𒆜': 'KASKAL',
  '𒆝': 'KASKAL LAGAB TIMES U OVER LAGAB TIMES U',
  '𒆞': 'KASKAL OVER KASKAL LAGAB TIMES U OVER LAGAB TIMES U',
  '𒆟': 'KESH2',
  '𒆠': 'KI',
  '𒆡': 'KI TIMES BAD',
  '𒆢': 'KI TIMES U',
  '𒆣': 'KI TIMES UD',
  '𒆤': 'KID',
  '𒆥': 'KIN',
  '𒆦': 'KISAL',
  '𒆧': 'KISH',
  '𒆨': 'KISIM5',
  '𒆩': 'KISIM5 OVER KISIM5',
  '𒆪': 'KU',
  '𒆫': 'KU OVER HI TIMES ASH2 KU OVER HI TIMES ASH2',
  '𒆬': 'KU3',
  '𒆭': 'KU4',
  '𒆮': 'KU4 VARIANT FORM',
  '𒆯': 'KU7',
  '𒆰': 'KUL',
  '𒆱': 'KUL GUNU',
  '𒆲': 'KUN',
  '𒆳': 'KUR',
  '𒆴': 'KUR OPPOSING KUR',
  '𒆵': 'KUSHU2',
  '𒆶': 'KWU318',
  '𒆷': 'LA',
  '𒆸': 'LAGAB',
  '𒆹': 'LAGAB TIMES A',
  '𒆺': 'LAGAB TIMES A PLUS DA PLUS HA',
  '𒆻': 'LAGAB TIMES A PLUS GAR',
  '𒆼': 'LAGAB TIMES A PLUS LAL',
  '𒆽': 'LAGAB TIMES AL',
  '𒆾': 'LAGAB TIMES AN',
  '𒆿': 'LAGAB TIMES ASH ZIDA TENU',
  '𒇀': 'LAGAB TIMES BAD',
  '𒇁': 'LAGAB TIMES BI',
  '𒇂': 'LAGAB TIMES DAR',
  '𒇃': 'LAGAB TIMES EN',
  '𒇄': 'LAGAB TIMES GA',
  '𒇅': 'LAGAB TIMES GAR',
  '𒇆': 'LAGAB TIMES GUD',
  '𒇇': 'LAGAB TIMES GUD PLUS GUD',
  '𒇈': 'LAGAB TIMES HA',
  '𒇉': 'LAGAB TIMES HAL',
  '𒇊': 'LAGAB TIMES HI TIMES NUN',
  '𒇋': 'LAGAB TIMES IGI GUNU',
  '𒇌': 'LAGAB TIMES IM',
  '𒇍': 'LAGAB TIMES IM PLUS HA',
  '𒇎': 'LAGAB TIMES IM PLUS LU',
  '𒇏': 'LAGAB TIMES KI',
  '𒇐': 'LAGAB TIMES KIN',
  '𒇑': 'LAGAB TIMES KU3',
  '𒇒': 'LAGAB TIMES KUL',
  '𒇓': 'LAGAB TIMES KUL PLUS HI PLUS A',
  '𒇔': 'LAGAB TIMES LAGAB',
  '𒇕': 'LAGAB TIMES LISH',
  '𒇖': 'LAGAB TIMES LU',
  '𒇗': 'LAGAB TIMES LUL',
  '𒇘': 'LAGAB TIMES ME',
  '𒇙': 'LAGAB TIMES ME PLUS EN',
  '𒇚': 'LAGAB TIMES MUSH',
  '𒇛': 'LAGAB TIMES NE',
  '𒇜': 'LAGAB TIMES SHE PLUS SUM',
  '𒇝': 'LAGAB TIMES SHITA PLUS GISH PLUS ERIN2',
  '𒇞': 'LAGAB TIMES SHITA PLUS GISH TENU',
  '𒇟': 'LAGAB TIMES SHU2',
  '𒇠': 'LAGAB TIMES SHU2 PLUS SHU2',
  '𒇡': 'LAGAB TIMES SUM',
  '𒇢': 'LAGAB TIMES TAG',
  '𒇣': 'LAGAB TIMES TAK4',
  '𒇤': 'LAGAB TIMES TE PLUS A PLUS SU PLUS NA',
  '𒇥': 'LAGAB TIMES U',
  '𒇦': 'LAGAB TIMES U PLUS A',
  '𒇧': 'LAGAB TIMES U PLUS U PLUS U',
  '𒇨': 'LAGAB TIMES U2 PLUS ASH',
  '𒇩': 'LAGAB TIMES UD',
  '𒇪': 'LAGAB TIMES USH',
  '𒇫': 'LAGAB SQUARED',
  '𒇬': 'LAGAR',
  '𒇭': 'LAGAR TIMES SHE',
  '𒇮': 'LAGAR TIMES SHE PLUS SUM',
  '𒇯': 'LAGAR GUNU',
  '𒇰': 'LAGAR GUNU OVER LAGAR GUNU SHE',
  '𒇱': 'LAHSHU',
  '𒇲': 'LAL',
  '𒇳': 'LAL TIMES LAL',
  '𒇴': 'LAM',
  '𒇵': 'LAM TIMES KUR',
  '𒇶': 'LAM TIMES KUR PLUS RU',
  '𒇷': 'LI',
  '𒇸': 'LIL',
  '𒇹': 'LIMMU2',
  '𒇺': 'LISH',
  '𒇻': 'LU',
  '𒇼': 'LU TIMES BAD',
  '𒇽': 'LU2',
  '𒇾': 'LU2 TIMES AL',
  '𒇿': 'LU2 TIMES BAD',
  '𒈀': 'LU2 TIMES ESH2',
  '𒈁': 'LU2 TIMES ESH2 TENU',
  '𒈂': 'LU2 TIMES GAN2 TENU',
  '𒈃': 'LU2 TIMES HI TIMES BAD',
  '𒈄': 'LU2 TIMES IM',
  '𒈅': 'LU2 TIMES KAD2',
  '𒈆': 'LU2 TIMES KAD3',
  '𒈇': 'LU2 TIMES KAD3 PLUS ASH',
  '𒈈': 'LU2 TIMES KI',
  '𒈉': 'LU2 TIMES LA PLUS ASH',
  '𒈊': 'LU2 TIMES LAGAB',
  '𒈋': 'LU2 TIMES ME PLUS EN',
  '𒈌': 'LU2 TIMES NE',
  '𒈍': 'LU2 TIMES NU',
  '𒈎': 'LU2 TIMES SI PLUS ASH',
  '𒈏': 'LU2 TIMES SIK2 PLUS BU',
  '𒈐': 'LU2 TIMES TUG2',
  '𒈑': 'LU2 TENU',
  '𒈒': 'LU2 CROSSING LU2',
  '𒈓': 'LU2 OPPOSING LU2',
  '𒈔': 'LU2 SQUARED',
  '𒈕': 'LU2 SHESHIG',
  '𒈖': 'LU3',
  '𒈗': 'LUGAL',
  '𒈘': 'LUGAL OVER LUGAL',
  '𒈙': 'LUGAL OPPOSING LUGAL',
  '𒈚': 'LUGAL SHESHIG',
  '𒈛': 'LUH',
  '𒈜': 'LUL',
  '𒈝': 'LUM',
  '𒈞': 'LUM OVER LUM',
  '𒈟': 'LUM OVER LUM GAR OVER GAR',
  '𒈠': 'MA',
  '𒈡': 'MA TIMES TAK4',
  '𒈢': 'MA GUNU',
  '𒈣': 'MA2',
  '𒈤': 'MAH',
  '𒈥': 'MAR',
  '𒈦': 'MASH',
  '𒈧': 'MASH2',
  '𒈨': 'ME',
  '𒈩': 'MES',
  '𒈪': 'MI',
  '𒈫': 'MIN',
  '𒈬': 'MU',
  '𒈭': 'MU OVER MU',
  '𒈮': 'MUG',
  '𒈯': 'MUG GUNU',
  '𒈰': 'MUNSUB',
  '𒈱': 'MURGU2',
  '𒈲': 'MUSH',
  '𒈳': 'MUSH TIMES A',
  '𒈴': 'MUSH TIMES KUR',
  '𒈵': 'MUSH TIMES ZA',
  '𒈶': 'MUSH OVER MUSH',
  '𒈷': 'MUSH OVER MUSH TIMES A PLUS NA',
  '𒈸': 'MUSH CROSSING MUSH',
  '𒈹': 'MUSH3',
  '𒈺': 'MUSH3 TIMES A',
  '𒈻': 'MUSH3 TIMES A PLUS DI',
  '𒈼': 'MUSH3 TIMES DI',
  '𒈽': 'MUSH3 GUNU',
  '𒈾': 'NA',
  '𒈿': 'NA2',
  '𒉀': 'NAGA',
  '𒉁': 'NAGA INVERTED',
  '𒉂': 'NAGA TIMES SHU TENU',
  '𒉃': 'NAGA OPPOSING NAGA',
  '𒉄': 'NAGAR',
  '𒉅': 'NAM NUTILLU',
  '𒉆': 'NAM',
  '𒉇': 'NAM2',
  '𒉈': 'NE',
  '𒉉': 'NE TIMES A',
  '𒉊': 'NE TIMES UD',
  '𒉋': 'NE SHESHIG',
  '𒉌': 'NI',
  '𒉍': 'NI TIMES E',
  '𒉎': 'NI2',
  '𒉏': 'NIM',
  '𒉐': 'NIM TIMES GAN2 TENU',
  '𒉑': 'NIM TIMES GAR PLUS GAN2 TENU',
  '𒉒': 'NINDA2',
  '𒉓': 'NINDA2 TIMES AN',
  '𒉔': 'NINDA2 TIMES ASH',
  '𒉕': 'NINDA2 TIMES ASH PLUS ASH',
  '𒉖': 'NINDA2 TIMES GUD',
  '𒉗': 'NINDA2 TIMES ME PLUS GAN2 TENU',
  '𒉘': 'NINDA2 TIMES NE',
  '𒉙': 'NINDA2 TIMES NUN',
  '𒉚': 'NINDA2 TIMES SHE',
  '𒉛': 'NINDA2 TIMES SHE PLUS A AN',
  '𒉜': 'NINDA2 TIMES SHE PLUS ASH',
  '𒉝': 'NINDA2 TIMES SHE PLUS ASH PLUS ASH',
  '𒉞': 'NINDA2 TIMES U2 PLUS ASH',
  '𒉟': 'NINDA2 TIMES USH',
  '𒉠': 'NISAG',
  '𒉡': 'NU',
  '𒉢': 'NU11',
  '𒉣': 'NUN',
  '𒉤': 'NUN LAGAR TIMES GAR',
  '𒉥': 'NUN LAGAR TIMES MASH',
  '𒉦': 'NUN LAGAR TIMES SAL',
  '𒉧': 'NUN LAGAR TIMES SAL OVER NUN LAGAR TIMES SAL',
  '𒉨': 'NUN LAGAR TIMES USH',
  '𒉩': 'NUN TENU',
  '𒉪': 'NUN OVER NUN',
  '𒉫': 'NUN CROSSING NUN',
  '𒉬': 'NUN CROSSING NUN LAGAR OVER LAGAR',
  '𒉭': 'NUNUZ',
  '𒉮': 'NUNUZ AB2 TIMES ASHGAB',
  '𒉯': 'NUNUZ AB2 TIMES BI',
  '𒉰': 'NUNUZ AB2 TIMES DUG',
  '𒉱': 'NUNUZ AB2 TIMES GUD',
  '𒉲': 'NUNUZ AB2 TIMES IGI GUNU',
  '𒉳': 'NUNUZ AB2 TIMES KAD3',
  '𒉴': 'NUNUZ AB2 TIMES LA',
  '𒉵': 'NUNUZ AB2 TIMES NE',
  '𒉶': 'NUNUZ AB2 TIMES SILA3',
  '𒉷': 'NUNUZ AB2 TIMES U2',
  '𒉸': 'NUNUZ KISIM5 TIMES BI',
  '𒉹': 'NUNUZ KISIM5 TIMES BI U',
  '𒉺': 'PA',
  '𒉻': 'PAD',
  '𒉼': 'PAN',
  '𒉽': 'PAP',
  '𒉾': 'PESH2',
  '𒉿': 'PI',
  '𒊀': 'PI TIMES A',
  '𒊁': 'PI TIMES AB',
  '𒊂': 'PI TIMES BI',
  '𒊃': 'PI TIMES BU',
  '𒊄': 'PI TIMES E',
  '𒊅': 'PI TIMES I',
  '𒊆': 'PI TIMES IB',
  '𒊇': 'PI TIMES U',
  '𒊈': 'PI TIMES U2',
  '𒊉': 'PI CROSSING PI',
  '𒊊': 'PIRIG',
  '𒊋': 'PIRIG TIMES KAL',
  '𒊌': 'PIRIG TIMES UD',
  '𒊍': 'PIRIG TIMES ZA',
  '𒊎': 'PIRIG OPPOSING PIRIG',
  '𒊏': 'RA',
  '𒊐': 'RAB',
  '𒊑': 'RI',
  '𒊒': 'RU',
  '𒊓': 'SA',
  '𒊔': 'SAG NUTILLU',
  '𒊕': 'SAG',
  '𒊖': 'SAG TIMES A',
  '𒊗': 'SAG TIMES DU',
  '𒊘': 'SAG TIMES DUB',
  '𒊙': 'SAG TIMES HA',
  '𒊚': 'SAG TIMES KAK',
  '𒊛': 'SAG TIMES KUR',
  '𒊜': 'SAG TIMES LUM',
  '𒊝': 'SAG TIMES MI',
  '𒊞': 'SAG TIMES NUN',
  '𒊟': 'SAG TIMES SAL',
  '𒊠': 'SAG TIMES SHID',
  '𒊡': 'SAG TIMES TAB',
  '𒊢': 'SAG TIMES U2',
  '𒊣': 'SAG TIMES UB',
  '𒊤': 'SAG TIMES UM',
  '𒊥': 'SAG TIMES UR',
  '𒊦': 'SAG TIMES USH',
  '𒊧': 'SAG OVER SAG',
  '𒊨': 'SAG GUNU',
  '𒊩': 'SAL',
  '𒊪': 'SAL LAGAB TIMES ASH2',
  '𒊫': 'SANGA2',
  '𒊬': 'SAR',
  '𒊭': 'SHA',
  '𒊮': 'SHA3',
  '𒊯': 'SHA3 TIMES A',
  '𒊰': 'SHA3 TIMES BAD',
  '𒊱': 'SHA3 TIMES GISH',
  '𒊲': 'SHA3 TIMES NE',
  '𒊳': 'SHA3 TIMES SHU2',
  '𒊴': 'SHA3 TIMES TUR',
  '𒊵': 'SHA3 TIMES U',
  '𒊶': 'SHA3 TIMES U PLUS A',
  '𒊷': 'SHA6',
  '𒊸': 'SHAB6',
  '𒊹': 'SHAR2',
  '𒊺': 'SHE',
  '𒊻': 'SHE HU',
  '𒊼': 'SHE OVER SHE GAD OVER GAD GAR OVER GAR',
  '𒊽': 'SHE OVER SHE TAB OVER TAB GAR OVER GAR',
  '𒊾': 'SHEG9',
  '𒊿': 'SHEN',
  '𒋀': 'SHESH',
  '𒋁': 'SHESH2',
  '𒋂': 'SHESHLAM',
  '𒋃': 'SHID',
  '𒋄': 'SHID TIMES A',
  '𒋅': 'SHID TIMES IM',
  '𒋆': 'SHIM',
  '𒋇': 'SHIM TIMES A',
  '𒋈': 'SHIM TIMES BAL',
  '𒋉': 'SHIM TIMES BULUG',
  '𒋊': 'SHIM TIMES DIN',
  '𒋋': 'SHIM TIMES GAR',
  '𒋌': 'SHIM TIMES IGI',
  '𒋍': 'SHIM TIMES IGI GUNU',
  '𒋎': 'SHIM TIMES KUSHU2',
  '𒋏': 'SHIM TIMES LUL',
  '𒋐': 'SHIM TIMES MUG',
  '𒋑': 'SHIM TIMES SAL',
  '𒋒': 'SHINIG',
  '𒋓': 'SHIR',
  '𒋔': 'SHIR TENU',
  '𒋕': 'SHIR OVER SHIR BUR OVER BUR',
  '𒋖': 'SHITA',
  '𒋗': 'SHU',
  '𒋘': 'SHU OVER INVERTED SHU',
  '𒋙': 'SHU2',
  '𒋚': 'SHUBUR',
  '𒋛': 'SI',
  '𒋜': 'SI GUNU',
  '𒋝': 'SIG',
  '𒋞': 'SIG4',
  '𒋟': 'SIG4 OVER SIG4 SHU2',
  '𒋠': 'SIK2',
  '𒋡': 'SILA3',
  '𒋢': 'SU',
  '𒋣': 'SU OVER SU',
  '𒋤': 'SUD',
  '𒋥': 'SUD2',
  '𒋦': 'SUHUR',
  '𒋧': 'SUM',
  '𒋨': 'SUMASH',
  '𒋩': 'SUR',
  '𒋪': 'SUR9',
  '𒋫': 'TA',
  '𒋬': 'TA ASTERISK',
  '𒋭': 'TA TIMES HI',
  '𒋮': 'TA TIMES MI',
  '𒋯': 'TA GUNU',
  '𒋰': 'TAB',
  '𒋱': 'TAB OVER TAB NI OVER NI DISH OVER DISH',
  '𒋲': 'TAB SQUARED',
  '𒋳': 'TAG',
  '𒋴': 'TAG TIMES BI',
  '𒋵': 'TAG TIMES GUD',
  '𒋶': 'TAG TIMES SHE',
  '𒋷': 'TAG TIMES SHU',
  '𒋸': 'TAG TIMES TUG2',
  '𒋹': 'TAG TIMES UD',
  '𒋺': 'TAK4',
  '𒋻': 'TAR',
  '𒋼': 'TE',
  '𒋽': 'TE GUNU',
  '𒋾': 'TI',
  '𒋿': 'TI TENU',
  '𒌀': 'TIL',
  '𒌁': 'TIR',
  '𒌂': 'TIR TIMES TAK4',
  '𒌃': 'TIR OVER TIR',
  '𒌄': 'TIR OVER TIR GAD OVER GAD GAR OVER GAR',
  '𒌅': 'TU',
  '𒌆': 'TUG2',
  '𒌇': 'TUK',
  '𒌈': 'TUM',
  '𒌉': 'TUR',
  '𒌊': 'TUR OVER TUR ZA OVER ZA',
  '𒌋': 'U',
  '𒌌': 'U GUD',
  '𒌍': 'U U U',
  '𒌎': 'U OVER U PA OVER PA GAR OVER GAR',
  '𒌏': 'U OVER U SUR OVER SUR',
  '𒌐': 'U OVER U U REVERSED OVER U REVERSED',
  '𒌑': 'U2',
  '𒌒': 'UB',
  '𒌓': 'UD',
  '𒌔': 'UD KUSHU2',
  '𒌕': 'UD TIMES BAD',
  '𒌖': 'UD TIMES MI',
  '𒌗': 'UD TIMES U PLUS U PLUS U',
  '𒌘': 'UD TIMES U PLUS U PLUS U GUNU',
  '𒌙': 'UD GUNU',
  '𒌚': 'UD SHESHIG',
  '𒌛': 'UD SHESHIG TIMES BAD',
  '𒌜': 'UDUG',
  '𒌝': 'UM',
  '𒌞': 'UM TIMES LAGAB',
  '𒌟': 'UM TIMES ME PLUS DA',
  '𒌠': 'UM TIMES SHA3',
  '𒌡': 'UM TIMES U',
  '𒌢': 'UMBIN',
  '𒌣': 'UMUM',
  '𒌤': 'UMUM TIMES KASKAL',
  '𒌥': 'UMUM TIMES PA',
  '𒌦': 'UN',
  '𒌧': 'UN GUNU',
  '𒌨': 'UR',
  '𒌩': 'UR CROSSING UR',
  '𒌪': 'UR SHESHIG',
  '𒌫': 'UR2',
  '𒌬': 'UR2 TIMES A PLUS HA',
  '𒌭': 'UR2 TIMES A PLUS NA',
  '𒌮': 'UR2 TIMES AL',
  '𒌯': 'UR2 TIMES HA',
  '𒌰': 'UR2 TIMES NUN',
  '𒌱': 'UR2 TIMES U2',
  '𒌲': 'UR2 TIMES U2 PLUS ASH',
  '𒌳': 'UR2 TIMES U2 PLUS BI',
  '𒌴': 'UR4',
  '𒌵': 'URI',
  '𒌶': 'URI3',
  '𒌷': 'URU',
  '𒌸': 'URU TIMES A',
  '𒌹': 'URU TIMES ASHGAB',
  '𒌺': 'URU TIMES BAR',
  '𒌻': 'URU TIMES DUN',
  '𒌼': 'URU TIMES GA',
  '𒌽': 'URU TIMES GAL',
  '𒌾': 'URU TIMES GAN2 TENU',
  '𒌿': 'URU TIMES GAR',
  '𒍀': 'URU TIMES GU',
  '𒍁': 'URU TIMES HA',
  '𒍂': 'URU TIMES IGI',
  '𒍃': 'URU TIMES IM',
  '𒍄': 'URU TIMES ISH',
  '𒍅': 'URU TIMES KI',
  '𒍆': 'URU TIMES LUM',
  '𒍇': 'URU TIMES MIN',
  '𒍈': 'URU TIMES PA',
  '𒍉': 'URU TIMES SHE',
  '𒍊': 'URU TIMES SIG4',
  '𒍋': 'URU TIMES TU',
  '𒍌': 'URU TIMES U PLUS GUD',
  '𒍍': 'URU TIMES UD',
  '𒍎': 'URU TIMES URUDA',
  '𒍏': 'URUDA',
  '𒍐': 'URUDA TIMES U',
  '𒍑': 'USH',
  '𒍒': 'USH TIMES A',
  '𒍓': 'USH TIMES KU',
  '𒍔': 'USH TIMES KUR',
  '𒍕': 'USH TIMES TAK4',
  '𒍖': 'USHX',
  '𒍗': 'USH2',
  '𒍘': 'USHUMX',
  '𒍙': 'UTUKI',
  '𒍚': 'UZ3',
  '𒍛': 'UZ3 TIMES KASKAL',
  '𒍜': 'UZU',
  '𒍝': 'ZA',
  '𒍞': 'ZA TENU',
  '𒍟': 'ZA SQUARED TIMES KUR',
  '𒍠': 'ZAG',
  '𒍡': 'ZAMX',
  '𒍢': 'ZE2',
  '𒍣': 'ZI',
  '𒍤': 'ZI OVER ZI',
  '𒍥': 'ZI3',
  '𒍦': 'ZIB',
  '𒍧': 'ZIB KABA TENU',
  '𒍨': 'ZIG',
  '𒍩': 'ZIZ2',
  '𒍪': 'ZU',
  '𒍫': 'ZU5',
  '𒍬': 'ZU5 TIMES A',
  '𒍭': 'ZUBUR',
  '𒍮': 'ZUM',
  '𒍯': 'KAP ELAMITE',
  '𒍰': 'AB TIMES NUN',
  '𒍱': 'AB2 TIMES A',
  '𒍲': 'AMAR TIMES KUG',
  '𒍳': 'DAG KISIM5 TIMES U2 PLUS MASH',
  '𒍴': 'DAG3',
  '𒍵': 'DISH PLUS SHU',
  '𒍶': 'DUB TIMES SHE',
  '𒍷': 'EZEN TIMES GUD',
  '𒍸': 'EZEN TIMES SHE',
  '𒍹': 'GA2 TIMES AN PLUS KAK PLUS A',
  '𒍺': 'GA2 TIMES ASH2',
  '𒍻': 'GE22',
  '𒍼': 'GIG',
  '𒍽': 'HUSH',
  '𒍾': 'KA TIMES ANSHE',
  '𒍿': 'KA TIMES ASH3',
  '𒎀': 'KA TIMES GISH',
  '𒎁': 'KA TIMES GUD',
  '𒎂': 'KA TIMES HI TIMES ASH2',
  '𒎃': 'KA TIMES LUM',
  '𒎄': 'KA TIMES PA',
  '𒎅': 'KA TIMES SHUL',
  '𒎆': 'KA TIMES TU',
  '𒎇': 'KA TIMES UR2',
  '𒎈': 'LAGAB TIMES GI',
  '𒎉': 'LU2 SHESHIG TIMES BAD',
  '𒎊': 'LU2 TIMES ESH2 PLUS LAL',
  '𒎋': 'LU2 TIMES SHU',
  '𒎌': 'MESH',
  '𒎍': 'MUSH3 TIMES ZA',
  '𒎎': 'NA4',
  '𒎏': 'NIN',
  '𒎐': 'NIN9',
  '𒎑': 'NINDA2 TIMES BAL',
  '𒎒': 'NINDA2 TIMES GI',
  '𒎓': 'NU11 ROTATED NINETY DEGREES',
  '𒎔': 'PESH2 ASTERISK',
  '𒎕': 'PIR2',
  '𒎖': 'SAG TIMES IGI GUNU',
  '𒎗': 'TI2',
  '𒎘': 'UM TIMES ME',
  '𒎙': 'U U',
}

export const OldPersianLetters = {
  // Independent vowels
  '𐎠': 'A',
  '𐎡': 'I',
  '𐎢': 'U',
  // Consonants
  '𐎣': 'Ka',
  '𐎤': 'Ku',
  '𐎥': 'Ga',
  '𐎦': 'Gu',
  '𐎧': 'Xa',
  '𐎨': 'Ca',
  '𐎩': 'Ja',
  '𐎪': 'Ji',
  '𐎫': 'Ta',
  '𐎬': 'Tu',
  '𐎭': 'Da',
  '𐎮': 'Di',
  '𐎯': 'Du',
  '𐎰': 'Tha',
  '𐎱': 'Pa',
  '𐎲': 'Ba',
  '𐎳': 'Fa',
  '𐎴': 'Na',
  '𐎵': 'Nu',
  '𐎶': 'Ma',
  '𐎷': 'Mi',
  '𐎸': 'Mu',
  '𐎹': 'Ya',
  '𐎺': 'Va',
  '𐎻': 'Vi',
  '𐎼': 'Ra',
  '𐎽': 'Ru',
  '𐎾': 'La',
  '𐎿': 'Sa',
  '𐏀': 'Za',
  '𐏁': 'Sha',
  '𐏂': 'Ssa',
  '𐏃': 'Ha',
  // Various signs
  '𐏈': 'Auramazdaa',
  '𐏉': 'Auramazdaa- 2 ',
  '𐏊': 'Auramazdaaha ',
  '𐏋': 'Xshaayathiya ',
  '𐏌': 'Dahyaaush ',
  '𐏍': 'Dahyaaush-2 ',
  '𐏎': 'Baga',
  '𐏏': 'Buumish',
  // Punctuation
  '𐏐': ' ',
  // Numbers
  '𐏑': '1',
  '𐏒': '2',
  '𐏓': '10',
  '𐏔': '20',
  '𐏕': '100',
}
