name: Build and Upload github pages

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 20.11.0
      uses: actions/setup-node@v3
      with:
        node-version: 20.11.0
        cache: 'npm'
    - run: npm ci
    - run: npm run build
    - name: Upload GitHub Pages artifact
      uses: actions/upload-pages-artifact@v3.0.1
      with:
        name: github-pages
        path:  dist
        
              
